tweaked xiin exit error handling

diff --git a/inxi b/inxi
--- a/inxi
+++ b/inxi
@@ -1261,7 +1261,12 @@ debug_data_collector()
 			error_handler 17 'xiin'
 		elif [[ -n $( grep -s 'checkPython' xiin ) ]];then
 			echo 'Running xiin tool now on /sys...'
-			python ./xiin -d /sys -f $xiin_data_file || error_handler 19 'xiin'
+			python ./xiin -d /sys -f $xiin_data_file
+			if [[ $? -ne 0 ]];then
+				echo "xiin exited with error $? - removing data file before exiting."
+				rm -f $xiin_data_file
+				error_handler 19 'xiin'
+			fi
 		else
 			error_handler 18 'xiin'
 		fi
